spring.application.name=api-rest
spring.data.mongodb.uri=mongodb://localhost:27017/reseau_culinaire

security.jwt.secret-key=Qm1u3V8mBKYhKXKxWmZ2hXqFhP7qv5o0o9q8Sg1hJn3xZt6yGf2uLk9pRw2aBt6Y
security.jwt.expiration-time=86400000

recommendation.api.url=http://localhost:5000
